### PR TITLE
Develop tuberculosis

### PR DESCRIPTION
**Pull request by federicamontes**
added script for generating tuberculosis data
cases: use baseline, enforce locality, enforce locality + numa

### CODE REVIEW

**Comment by federicamontes** [comment]
new modifications regarding:
* list management, scan_list_for_stats called everytime a list is updated
* event content sent to the same region (passed by reference)

**Comment by RomoloMarotta** [comment]
should be already included into the new code of  repro/tomacs-candidate

**Review by RomoloMarotta — COMMENTED** [review]
already included into repro/tomacs-candidate-dev

**Comment by RomoloMarotta** [comment]
already included into repro/tomacs-candidate-dev

**Pull request closed without merging**
